### ISSUE TITLE
这个工程在window下运行没问题，但是部署到centos7上测试，就报错：java.lang.ClassCastException: com.plugin.impl.PluginImpl cannot be cast to com.plugin.PluginInterface

### ISSUE THREAD

**Issue by wz2326** [zlt2000/springs-boot-plugin-test#1]
这个工程在window下运行没问题，但是部署到centos7上测试，就报错：java.lang.ClassCastException: com.plugin.impl.PluginImpl cannot be cast to com.plugin.PluginInterface，请问作者在linux上测试过么？求教作者知道这是什么原因引起的吗

**Comment by HaiChecker** [comment]
解决了吗？

**Comment by qf8505** [comment]
https://github.com/qf8505/springs-boot-plugin-test.git已经解决，由于是使用的接口不是同一个导致的

**Comment by zlt2000** [comment]
最新的代码经过测试centos7和windows系统都正常
